name: Build and Test React App

on:
  push:
    branches:
      - Final-Project

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Test application
        run: npm run test --passWithNoTests
