name: Build and Test React App

on:
  push:
    branches:
      - Final-Project

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Test application
<<<<<<< HEAD
        run: npm run test -- --watch=false

      - name: Lint application
        run: npm run lint
=======
        run: npm run test
>>>>>>> 86794c9f79f898937813a64f10765cc4752c974b
