name: Node.js CI

on:
  push:
    branches: [Final-Project]
  pull_request:
    branches: [Final-Project]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.2.0"

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to start
        run: sleep 10

      - name: Test server with curl
        run: curl -f http://localhost:3000 || exit 1

      - name: Check npm start
        run: |
          if ! npm start; then
            echo "npm start failed"
            exit 1
          fi
